name: 'Terraform'

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_DEFAULT_REGION: "eu-south-2"
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./Project02/terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download tfvars from AWS Secrets Manager
      run: |
          aws secretsmanager get-secret-value \
            --secret-id "terraform.tfvars" \
            --query SecretString \
            --output text > terraform.tfvars
    - name: Set up terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.14.8

    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Format
      run: terraform fmt -recursive

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
